### ISSUE TITLE
ACDB.exe is flagged as a threat by Windows Security

### ISSUE THREAD

**Issue by beebase** [jgyo/ACDB#1]
It thinks it's malware and quarantines it automatically. (Trojan:Win32/Sabsik.TE.A!ml)

**Comment by jgyo** [comment]
Thank you. Malwarebytes was flagging ACDB.EXE with a different title, but only because the exe was so new. What virus software is flagging it on your system?

If you installed from the released code here, or from flightsim.to, the flag is a false positive. Until the virus software becomes aware of the file, you may need to exclude it from your virus software's tests.

**Comment by jgyo** [comment]
FYI this is the wrong repository for ACDB support. I'll be deleting this repository in a day or two to remove the confusion, but this was created in error. The correct repository is https://github.com/jgyo/CLBuilder

**Comment by beebase** [comment]
It's flagged by the default windows security. I'll disable for time being. 
Thanks for replying. I'll be following correct repo.

**Comment by jgyo** [comment]
Thanks again. I use Microsoft security on my system too, and it doesn't flag it on mine. I'm not sure why yours would flag it, and mine does not unless we are on different antivirus updates.

I made a minor change that might help, however. I haven't released it yet, but I'll try to get it out in the next 48 hours.

**Comment by beebase** [comment]
In the meantime, I'm not getting flags anymore. Al good. 👍
